### ISSUE TITLE
Latest K2 update breaks "first aid" entities

### ISSUE THREAD

**Issue by brainfork** [dslam127/xtreme-fishing#1]
![Screenshot 2023-01-27 205000](https://user-images.githubusercontent.com/2246606/215238815-ceeab78e-8565-4ac2-868f-372c31212463.png)

Removing the first aid entities fixes the problem, probably not an ideal fix though

**Comment by nihilistzsche** [comment]
I'm trying to figure out why this errors, but looking through the Krastorio2 and space-exploration sources (which these upgrades change these two a lot) isn't showing anything obvious, but I'll let you know if I have any success.

EDIT: Actually, I might understand whats happening here, going to try something.
Confirmed my suspicion, I'll have pull-request with fix in a few minutes.
